### ISSUE TITLE
Failed to update auto layout status

### ISSUE THREAD

**Issue by bluemix** [xaviermerino/XMSegmentedControl#16]
In the storyboard, when I add a view and assigned it to XMSegmentedControl, I get the following error:

```
Failed to update auto layout status: The agent raised a "CALayerInvalidGeometry" exception: CALayer position contains NaN: [nan 36]
```

and the app can't be executed.

**Comment by xaviermerino** [comment]
Hello. I just approved some changes so that might have broken something. Now this error appears because in order to distribute the space of the control among tabs we divide the total width by the amount of segments that you wish to create. If the segments are 0 (either because something didn't get set properly or because you are not giving it segments) then it will break. 

If you check the closed issues you will be able to find a fix. I'll look into it as soon as possible.

**Comment by bb-git** [comment]
I have the same error using interface builder. I didn't change the default settings, as i do this in the code.
